In [3]:
# Question 1
# Arrays

import numpy

def arrays(arr):
    return numpy.array(arr[::-1], float)

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

-4 2 5 -2
[-2.  5.  2. -4.]


In [4]:
# Question 2
# Shape and Reshape

import numpy as np

arr=input().strip().split(' ')
arr=np.array(arr,int)
print(np.reshape(arr,(3,3)))


2 4 6 2 4 6 3 9 45
[[ 2  4  6]
 [ 2  4  6]
 [ 3  9 45]]


In [6]:
# Question 3
# Transpose and Flatten


import numpy as np

n,m=input().strip().split(" ")
k=[]
for i in range(int(n)):
    a=input().strip().split(" ")
    k.append(a)

n=np.array(k,int)
print(n.transpose())
print(n.flatten())

1 2
2 2
[[2]
 [2]]
[2 2]


In [7]:
# Question 4
# concatenate


import numpy as np

n, m, p = map(int, input().split())    

source = " ".join(input() for i in range(n))  
matrix1 = np.array(source.split(), int)
matrix1.shape = (n, p)

source = " ".join(input() for j in range(m)) 
matrix2 = np.array(source.split(), int)    
matrix2.shape = (m, p)

print(np.concatenate((matrix1, matrix2), axis=0)) 

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [9]:
# Question 5
# Sum and Prod


import numpy

N,M = input().split()

lst = []
for i in range(int(N)):
    lst.append(input().split())

array = numpy.array(lst, int)
row_sum = numpy.sum(array, axis = 0)
print(numpy.prod(row_sum))

2 2
1 2
3 4
24


In [10]:
# Question 6
# Zeroes and Ones

import numpy
d = tuple(  map(int,(input().split())     ))

arr1 = numpy.zeros((d), dtype = numpy.int)
print(arr1)
    
arr2 = numpy.ones((d), dtype = numpy.int)
print(arr2)

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [11]:
# Question 7
# Eye and Identity


import numpy

numpy.set_printoptions(sign=' ')
print(numpy.eye(*map(int, input().split())))

2 2
[[ 1.  0.]
 [ 0.  1.]]


In [12]:
# Question 8
# Array Mathematics

import numpy

n,m = map(int,input().split())
a = numpy.array([input().split()],int)
b = numpy.array([input().split()],int)
print (a+b,a-b,a*b,a//b,a%b,a**b,sep='\n')

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [14]:
# Question 9
# Floor, Ceil and Rint

import numpy as np
np.set_printoptions(legacy = '1.13')
ar = np.array(input().strip().split(), float)
print(np.floor(ar), np.ceil(ar), np.rint(ar), sep = "\n")

1.1 2.2 7.6 3.5
[ 1.  2.  7.  3.]
[ 2.  3.  8.  4.]
[ 1.  2.  8.  4.]


In [15]:
# Question 10
# Min and Max

import numpy
arr=[]
n,m=map(int,input().split())
for row in range(n):
    my_arr=list(map(int,input().split()))
    arr.append(my_arr)
my_array=numpy.array(arr)
result=numpy.min(my_array, axis = 1)
print(max(result))

2 4
2 3
5 6
5


In [17]:
# Question 11
# Dot and Cross

import numpy as np

n = int(input())
a = np.array([input().split() for i in range(n)], int)
b = np.array([input().split() for j in range(n)], int)
print(np.dot(a, b))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [18]:
# Question 12
# Inner and Outer

import numpy
A=numpy.array(input().split(),int)
B=numpy.array(input().split(),int)
print(numpy.inner(A,B))
print(numpy.outer(A,B))

0 1 
2 3
3
[[0 0]
 [2 3]]


In [20]:
# Question 13
# Polynomials

n = list(map(float,input().split()));
m = input();
print(numpy.polyval(n,int(m)));

1.1 2 3
3
18.9


In [22]:
# Question 14
# Linear Algebra

import numpy as np
n = int(input())

arr = np.array([input().split() for i in range(n)], float)
arr_det = np.linalg.det(arr)

print(round(arr_det, 2))

2
1.1 3.3
2.2 4.4
-2.42


In [23]:
# Question 15
# Mean, Var and Std

import numpy as np 

n,m = map(int, input().split())
b = []
for i in range(n):
    a = list(map(int, input().split()))
    b.append(a)

b = np.array(b)

np.set_printoptions(legacy='1.13')
print(np.mean(b, axis = 1))
print(np.var(b, axis = 0))
print(np.std(b))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875
